
version: 2

models:
  - name: calendar_silver
    description: "Camada silver da tabela calendar"
    columns:
      - name: listing_id
        description: "Identificador único para cada imóvel"
        tests:
          - not_null
      - name: date
        description: "Data específica para a qual a consulta é feita"
        tests:
          - not_null
      - name: available
        description: "Indica se o imóvel está disponível para reserva nessa data (booleano)"
        tests:
          - not_null

  - name: reviews_silver
    description: "Camada silver da tabela reviews"
    columns:
      - name: review_id
        description: "Identificador único para cada avaliação"
        tests:
          - unique
          - not_null
      - name: listing_id
        description: "Identificador do imóvel ao qual a avaliação está associada"
        tests:
          - not_null
      - name: date
        description: "Data em que a avaliação foi feita"
        tests:
          - not_null
      - name: comments
        description: "Conteúdo da avaliação"
        tests:
          - not_null

  - name: listings_silver
    description: "Camada silver da tabela listings"
    columns:
      - name: listing_id
        description: "Identificador único de cada imóvel"
        tests:
          - unique
          - not_null
      - name: price
        description: "Preço por noite"
        tests:
          - not_null
      - name: property_type
        description: "Tipo de imóvel para locação"
        tests:
          - not_null
      - name: review_scores_rating
        description: "Pontuação geral da avaliação do imóvel"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  # Pontuação entre 0 e 100
              max_value: 100
      - name: host_id
        description: "Identificador do anfitrião do imóvel"
        tests:
          - not_null